feat: update developer portal for swap
LedgerHQ/developer-portal pull request #173
Opened 2024-04-15 15:17 UTC by tsouchon-ledger

2024-05-03 16:12 UTC, cpellizzari-ledger requested changes

2024-05-03 16:12 UTC, cpellizzari-ledger commented on public/exchange/openapi/swap-provider-openapi.yml
>          nonce:
please remove the amountToWallet field, we don't actually send it (for moonpay, changelly, cic) and there is no need for it

2024-05-06 14:12 UTC, tsouchon-ledger commented on public/exchange/openapi/swap-provider-openapi.yml
> +          description: Value between 0 to 1 (0.1 => 10%) to describe the difference between the quote and the real value of the exchange
not in required section ^^

2024-05-14 09:34 UTC, cpellizzari-ledger requested changes

2024-05-14 09:34 UTC, cpellizzari-ledger commented on public/exchange/openapi/swap-provider-openapi.yml
> +          description: Value between 0 to 1 (0.1 => 10%) to describe the difference between the quote and the real value of the exchange
This leaves too much room for interpretation actually... Let's replace slippageRange with 2 fields, minSlippage (string, ex "0.01") and maxSlippage (string, ex "0.3") instead. sorry...

2024-05-14 09:34 UTC, cpellizzari-ledger commented on public/exchange/openapi/swap-provider-openapi.yml
> +          description: Value between 0 to 1 (0.1 => 10%) to describe the difference between the quote and the real value of the exchange
please use "Value between 0 to 1 (0.1 => 10%). Maximum difference between the amount the user has seen in his quote and the amount he might finally receive, as a ratio of the quoted amount. Otherwise, the user should be asked for his consent to the new trade or reimbursed in original coin."
Here and on defaultSlippage field bellow.

2024-05-14 09:34 UTC, cpellizzari-ledger commented on public/exchange/openapi/swap-provider-openapi.yml
>          nonce:
up ^

2024-05-14 09:34 UTC, cpellizzari-ledger commented on public/exchange/openapi/swap-provider-openapi.yml
> +                amount: 1.337
we want all numbers to be serialized as string, to avoid precision loss issues. Please adapt the amount field type.
(Even if it is not what moonpay has implemented)

2024-05-15 10:13 UTC, cpellizzari-ledger approved these changes

2024-05-21 13:24 UTC, merged