Add clarification on uniqueness of swapId in swap open api
LedgerHQ/developer-portal pull request #197
Opened 2024-05-24 06:49 UTC by cpellizzari-ledger

2024-05-24 07:14 UTC, CremaFR approved these changes
Perfect ! thank you

2024-05-27 09:06 UTC, pdesreux-ledger requested changes

2024-05-27 09:06 UTC, pdesreux-ledger commented on public/exchange/openapi/swap-provider-openapi.yml
> +          description: provider's id of the ongoing swap transaction. This will be used by Ledger's backend to retrieve the status of user swap transaction. A unique id must be generated each time th
Error due to the presence of character` :` in the description at line 499. 
Solution: Replace the character with `=`, or add quotes ` 

>  ... with a same **`quoteId`:`quoteId != swapId`**.

2024-05-27 12:33 UTC, pdesreux-ledger approved these changes

2024-05-27 12:40 UTC, merged