Swap ftx update
LedgerHQ/developer-portal pull request #348
Opened 2022-02-22 15:54 UTC by pdesreux-ledger

Update the FTX documentation to become a swap provider

2022-02-22 16:48 UTC, chabroA requested changes

2022-02-22 16:48 UTC, chabroA commented on _docs/swap/how-to.md
> +- **Output**: binaryPayload, signature. <br>
Wouldn't change that since I believe the backend API still expect the data as `payload` and  `payload_signature`

2022-02-22 16:48 UTC, chabroA commented on _docs/swap/how-to.md
> +- `binaryPayload`: the swap parameters are assembled in a [protobuf](https://developers.google.com/protocol-buffers) message. Then using the protobuf tools you can do a [binary encoding](https://deve
```suggestion
- `binaryPayload`: the swap parameters are assembled in a [protobuf](https://developers.google.com/protocol-buffers) message. Then using the protobuf tools you can do a [binary encoding](https://developers.google.com/protocol-buffers/docs/encoding) of the protobuf to get a Byte Array. Finally, with [hex encoding](http://fileformats.archiveteam.org/wiki/Hex_encoding) you get the `binaryPayload` field.  
```

2022-02-22 16:48 UTC, chabroA commented on _docs/swap/how-to.md
> +- `providerSig.header.alg` - the algorithm used for the signature: “secp256k1”.
Don't know / not sure about that. Would need to confirm with @lcastillo-ledger and / or backend team (that may probably use this)

2022-02-22 17:38 UTC, pdesreux-ledger commented on _docs/swap/how-to.md
> +- `providerSig.header.alg` - the algorithm used for the signature: “secp256k1”.
Revert to ES256 for now, before confirmation

2022-02-22 17:38 UTC, pdesreux-ledger commented on _docs/swap/how-to.md
> +- **Output**: binaryPayload, signature. <br>
Revert to `payload` and `payload_signature`

2022-02-23 08:56 UTC, chabroA approved these changes

2022-02-23 09:38 UTC, merged

2022-02-25 11:44 UTC, YBadiss commented on _docs/swap/how-to.md
> +- `providerSig.header.alg` - the algorithm used for the signature: “secp256k1”.
I had a look at this in the past:

`ES256 == ECDSA using P-256 and SHA-256`, see https://www.rfc-editor.org/rfc/rfc7518#section-3.1

But that's not really correct as `P-256` could refer to `secp256r1` when we want `secp256k1` here.

I think we should be saying `Signed using secp256k1, with SHA-256 as its hash function` which is more precise.

2022-02-25 14:15 UTC, pdesreux-ledger commented on _docs/swap/how-to.md
> +- `providerSig.header.alg` - the algorithm used for the signature: “secp256k1”.
Done !

2022-03-02 17:26 UTC, chabroA commented
@pdesreux-ledger we would actually need to reverse this.
For context, we agreed with @lcastillo-ledger and the backend team (cc. @vbergeron-ledger) that we would stick with the initial standard