Add CodeQL documentation in security page
LedgerHQ/developer-portal pull request #429
Opened 2022-07-06 13:11 UTC by mlafon-ledger

2022-07-08 12:17 UTC, yhql commented on _docs/nano-app/secure-app.md
> +    name: Analyse
"analysis" rather ?

2022-07-08 12:17 UTC, yhql commented on _docs/nano-app/secure-app.md
> +In order to increase the security of your code you can add static analysis based on [CodeQL](https://codeql.github.com/docs/codeql-overview/) to make security checks.
minor: "to perform security checks"

2022-07-08 12:17 UTC, yhql commented on _docs/nano-app/secure-app.md
> +You have to initialise elements needed to build your Ledger app. You also have to add the languages used in your code so CodeQL could analyse it in the right way.
minor: "You have to initialize"

2022-07-08 12:17 UTC, yhql commented on _docs/nano-app/secure-app.md
> +	- You have to tell which language will be used and what are the queries you want to run. Please chose the security-and-quality queries.
minor: "Please choose the `security-and-quality` queries." (choose + quotes around the query name)

2022-07-08 12:17 UTC, yhql commented on _docs/nano-app/secure-app.md
> +Next on your GitHub security view in the “Code scanning alerts” panel you will see all the results of the CodeQl analysis. If you configure CodeQL to be run when a pull request (PR) on some branches
Could we add a screenshot to illustrate this?

2022-07-08 15:08 UTC, fcipollone-ledger commented on _docs/nano-app/secure-app.md
> +You have to initialise elements needed to build your Ledger app. You also have to add the languages used in your code so CodeQL could analyse it in the right way.
agreed

2022-07-08 15:15 UTC, fcipollone-ledger commented on _docs/nano-app/secure-app.md
> +	- You have to tell which language will be used and what are the queries you want to run. Please chose the security-and-quality queries.
agreed

2022-07-08 15:17 UTC, fcipollone-ledger commented on _docs/nano-app/secure-app.md
> +Next on your GitHub security view in the “Code scanning alerts” panel you will see all the results of the CodeQl analysis. If you configure CodeQL to be run when a pull request (PR) on some branches
Good idea

2022-07-25 13:25 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +    name: Analyse
This is the default name generating by codeql if a user used the GUI of GitHub to create the file

2022-07-26 09:56 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +You have to initialise elements needed to build your Ledger app. You also have to add the languages used in your code so CodeQL could analyse it in the right way.
thanks ! fix in the last commit

2022-07-26 09:56 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +	- You have to tell which language will be used and what are the queries you want to run. Please chose the security-and-quality queries.
thanks ! fix in the last commit

2022-07-26 09:56 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +Next on your GitHub security view in the “Code scanning alerts” panel you will see all the results of the CodeQl analysis. If you configure CodeQL to be run when a pull request (PR) on some branches
thanks ! fix in the last commit

2022-07-26 10:04 UTC, fcipollone-ledger commented
Thank you Everyone

2022-07-26 12:18 UTC, yhql approved these changes

2022-08-18 13:57 UTC, jibeee requested changes
Please use the passive form instead of "You have to...".

Otherwise, explanations are pretty clear!

2022-08-18 13:57 UTC, jibeee commented on _docs/nano-app/secure-app.md
> +You can integrate it directly in your CI tool by creating a new yaml file: .github/workflows/codeql-workflow.yaml in your repository.
Not "directly in your CI tool". This file is specific to GitHub Actions.

2022-08-18 13:57 UTC, jibeee commented on _docs/nano-app/secure-app.md
> +In order to increase the security of your code you can add static analysis based on [CodeQL](https://codeql.github.com/docs/codeql-overview/) to perform security checks.
I'd use the root documentation link (<https://codeql.github.com/docs/>) instead of the link you provided.

2022-08-18 13:57 UTC, jibeee commented on _docs/nano-app/secure-app.md
> +You have a complete file example here: <https://github.com/LedgerHQ/app-boilerplate/blob/0cdb0059e4f374b796b25ed347202c5e4e3e558a/.github/workflows/codeql-workflow.yml>.
"A complete example file is available here: ..."

2022-08-18 13:57 UTC, jibeee commented on _docs/nano-app/secure-app.md
> +You can integrate it directly in your CI tool by creating a new yaml file: .github/workflows/codeql-workflow.yaml in your repository.
Additionally, use the passive form (here and below): "CodeQL can be directly integrated into your project by creating..."

2022-08-18 14:39 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +You can integrate it directly in your CI tool by creating a new yaml file: .github/workflows/codeql-workflow.yaml in your repository.
Thanks! I modify it in last version

2022-08-18 14:39 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +In order to increase the security of your code you can add static analysis based on [CodeQL](https://codeql.github.com/docs/codeql-overview/) to perform security checks.
Thanks! I modify it in last version

2022-08-18 14:39 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +You have a complete file example here: <https://github.com/LedgerHQ/app-boilerplate/blob/0cdb0059e4f374b796b25ed347202c5e4e3e558a/.github/workflows/codeql-workflow.yml>.
Thanks! I modify it in last version

2022-08-18 15:10 UTC, greenknot requested changes
2 minor comments

2022-08-18 15:10 UTC, greenknot commented on _docs/nano-app/secure-app.md
> +CodeQL can be directly integrated into your project by creating a new yaml file: .github/workflows/codeql-workflow.yaml in your repository.
Nitpick: use markdown syntax for file location (`.github/workflows/codeql-workflow.yaml` instead of .github/workflows/codeql-workflow.yaml)

2022-08-18 15:10 UTC, greenknot commented on _docs/nano-app/secure-app.md
> +A complete example file is available here: <https://github.com/LedgerHQ/app-boilerplate/blob/0cdb0059e4f374b796b25ed347202c5e4e3e558a/.github/workflows/codeql-workflow.yml>.
A complete [codeql-workflow.yml](https://github.com/LedgerHQ/app-boilerplate/blob/0cdb0059e4f374b796b25ed347202c5e4e3e558a/.github/workflows/codeql-workflow.yml) file is available in the repository of the Boilerplate app.

2022-08-18 15:21 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +CodeQL can be directly integrated into your project by creating a new yaml file: .github/workflows/codeql-workflow.yaml in your repository.
Thanks! I modify it in last version

2022-08-19 09:14 UTC, greenknot approved these changes
LGTM, thanks!

2022-08-19 09:30 UTC, jibeee requested changes

2022-08-19 09:30 UTC, jibeee commented on _docs/nano-app/secure-app.md
> +CodeQL can be directly integrated into your project by creating a new yaml file: `.github/workflows/codeql-workflow.yaml` in your repository.
"yaml" --> "YAML"

2022-08-19 09:30 UTC, jibeee commented on _docs/nano-app/secure-app.md
> +The first part of the file consists of an initialization of elements needed to build your Ledger app and a declaration of languages used in your code so CodeQL could analyse it in the right way.
"analyse" --> "analyze" (US spelling)

2022-08-19 09:30 UTC, jibeee commented on _docs/nano-app/secure-app.md
> +	- Declaration of which language will be used and what are the queries you want to run. Please choose the `security-and-quality` queries.
"and what are the queries you want to run" --> "and what the queries you want to run  are", maybe

2022-08-19 09:35 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +The first part of the file consists of an initialization of elements needed to build your Ledger app and a declaration of languages used in your code so CodeQL could analyse it in the right way.
Thanks! I modify it in last version

2022-08-19 09:35 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +	- Declaration of which language will be used and what are the queries you want to run. Please choose the `security-and-quality` queries.
Thanks! I modify it in last version

2022-08-19 09:36 UTC, mlafon-ledger commented on _docs/nano-app/secure-app.md
> +CodeQL can be directly integrated into your project by creating a new yaml file: `.github/workflows/codeql-workflow.yaml` in your repository.
Thanks! I modify it in last version

2022-08-19 09:38 UTC, jibeee approved these changes

2022-08-22 16:24 UTC, merged